In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.zeros((2,3))

In [10]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones((2,3))

In [12]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5 = np.identity(5)

In [14]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7 = np.linspace(10,20,10)

In [17]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
arr8 = arr7.copy()

In [19]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# Numpy important properties

In [22]:
arr1.shape

(9,)

In [23]:
arr9 = np.array([[1,2],[3,4]])

In [24]:
arr9.shape

(2, 2)

In [25]:
arr9.ndim

2

In [26]:
arr9.size

4

In [27]:
arr9.itemsize

4

In [28]:
arr9

array([[1, 2],
       [3, 4]])

In [29]:
arr9.dtype

dtype('int32')

In [30]:
arr9.astype("float")

array([[1., 2.],
       [3., 4.]])

# Python Lists Vs Arrays

In [31]:
lista = range(100)

In [32]:
lista

range(0, 100)

In [33]:
arr11 = np.arange(100)

In [34]:
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
import sys
print(sys.getsizeof(87)*len(lista))

2800


In [41]:
print(arr11.itemsize*arr11.size)

400


In [42]:
import time

In [47]:
x = range(10000000)
y= range(10000000,20000000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

3.338959217071533


In [48]:
a =np.arange(10000000)
b =np.arange(10000000,20000000)

start_time = time.time()
c = a+b
print(time.time()-start_time)

0.7589976787567139


# Indexing, slicing and Iteration

In [49]:
arr12 = np.arange(24)

In [50]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
arr12[2]

array([ 8,  9, 10, 11])

In [56]:
arr12[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [57]:
arr12
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [58]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Numpy Operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [59]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [60]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [61]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [62]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [64]:
arr1.dot(arr2)

130

In [65]:
arr1

array([1, 2, 3, 4, 5])

In [68]:
arr1

array([1, 2, 3, 4, 5])

In [69]:
arr2

array([ 6,  7,  8,  9, 10])

In [70]:
arr2>3

array([ True,  True,  True,  True,  True])

In [71]:
arr3=np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [72]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [73]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [74]:
arr4.max()

11

In [75]:
arr4.min()

6

In [76]:
arr4.min(axis=0)

array([6, 7])

In [77]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [78]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])